automation:
  - alias: Kitchen - Dishwasher - Run when price is at minimum
    id: '1640731367839'
    trigger:
    - platform: state
      entity_id: sensor.borasvagen_electricity_price
      attribute: intraday_price_ranking
      to: 1
    condition:
    - condition: or
      conditions:
      - condition: state
        entity_id: sensor.kitchen_dishwasher_operation_state
        state: inactive
      - condition: state
        entity_id: sensor.kitchen_dishwasher_operation_state
        state: ready
      - condition: state
        entity_id: sensor.kitchen_dishwasher_operation_state
        state: unavailable
    - condition: template
      value_template: '{{ as_timestamp(now() - timedelta(hours=8)) >= as_timestamp(states(''input_datetime.kitchen_dishwasher_last_run''))}}'
    - condition: state
      entity_id: input_boolean.home_travelling_mode
      state: 'off'
    action:
    - action: switch.turn_on
      data: {}
      target:
        entity_id:
        - switch.kitchen_dishwasher_power
    - action: notify.edward
      data:
        message: Dishwasher is starting...
      continue_on_error: true
      enabled: false
    - delay:
        hours: 0
        minutes: 0
        seconds: 10
        milliseconds: 0
      continue_on_error: true
    - action: switch.turn_on
      data: {}
      target:
        entity_id:
        - switch.kitchen_dishwasher_power
    - action: select.select_option
      target:
        entity_id:
          - select.kitchen_dishwasher_active_program
          # - select.kitchen_dishwasher_selected_program
      data:
        option: dishcare_dishwasher_program_quick_65
      continue_on_error: true
    - wait_for_trigger:
      - platform: state
        entity_id:
        - sensor.kitchen_dishwasher_operation_state
        to: run
      timeout:
        hours: 0
        minutes: 10
        seconds: 0
        milliseconds: 0
    - if:
      - condition: state
        entity_id: sensor.kitchen_dishwasher_operation_state
        state: run
      then:
      - action: input_datetime.set_datetime
        target:
          entity_id: input_datetime.kitchen_dishwasher_last_run
        data:
          timestamp: '{{ now().timestamp() }}'
        continue_on_error: true
      - action: notify.edward
        data:
          message: Dishwasher successfully started.
        continue_on_error: true
      else:
      - action: notify.group_home
        data:
          message: Failed to start the dishwasher.
        continue_on_error: true
    mode: restart

#home_connect:
  #client_id: !secret home_connect_client_id
  #client_secret: !secret home_connect_client_secret

input_datetime:
  kitchen_dishwasher_last_run:
    name: Kitchen - Dishwasher - Last run
    has_date: true
    has_time: true
    icon: mdi:dishwasher

template:
  - trigger:
    - id: Door
      platform: state
      entity_id:
        - binary_sensor.kitchen_dishwasher_door
      from:
        - "off"
        - "on"
      to:
        - "off"
        - "on"
    - id: Cycle
      platform: state
      entity_id:
        - sensor.kitchen_dishwasher_operation_state
      to:
        - "Run"
    binary_sensor:
      - name: Kitchen - Dishwasher - Door oppened after run
        unique_id: 39cd3a86-5db0-40a0-978d-29751413fc59
        availability: >-
          {{ states('sensor.kitchen_dishwasher_operation_state') not in ['unknown','unavailable']
          and states('binary_sensor.kitchen_dishwasher_door') not in ['unknown','unavailable'] }}
        state: "{{ trigger.id == 'Door' }}"
        attributes:
          triggered_by: "{{ trigger.entity_id }}"
          last_triggered: "{{ now() }}"
          trigger: "{{ trigger }}"
          door: "{{ states('binary_sensor.kitchen_dishwasher_door') }}"
          operation_state: "{{ states('sensor.kitchen_dishwasher_operation_state') }}"
  - sensor:
      - name: Kitchen - Dishwasher - Remaining program time
        unique_id: 504050ac-2309-491b-a944-783b5c116184
        unit_of_measurement: minutes
        state: >
          {% set remaining_seconds = states("sensor.borasvagen_dishwasher_remaining_program_time") | as_timestamp - now() | as_timestamp %}
          {% if remaining_seconds | int(0) > 0 %}
            {{ ((remaining_seconds | int(0)/60) | round(0), 0) | max }}
          {% else %}
            0
          {% endif %}
        #state_class: measurement
        availability: >
          {{
            is_state("sensor.borasvagen_dishwasher_operation_state", "Run") and
            has_value("sensor.borasvagen_dishwasher_remaining_program_time")
          }}
