binary_sensor:
  - name: Guest bathroom - Occupied
    platform: bayesian # https://www.home-assistant.io/integrations/bayesian/
    unique_id: 70b01e9d-d3ee-40ff-b0c2-bcafaba12039
    device_class: occupancy
    prior: 0.01
    probability_threshold: 0.5
    observations:
      - entity_id: sensor.guest_bathroom_motion_ratio_in_the_last_10m
        platform: numeric_state
        above: 0.1
        prob_given_true: 0.7
        prob_given_false: 0.1
      - entity_id: binary_sensor.guest_bathroom_motion_occupancy
        platform: state
        to_state: on
        prob_given_true: 0.8
        prob_given_false: 0.1
      - entity_id: binary_sensor.guest_bathroom_motion_iaszone
        platform: state
        to_state: on
        prob_given_true: 0.99
        prob_given_false: 0.25
      - entity_id: sensor.guest_bathroom_mirror_outlets_power
        platform: numeric_state
        above: 10
        prob_given_true: 0.9
        prob_given_false: 0.1
      - entity_id: input_boolean.home_empty
        platform: state
        to_state: on
        prob_given_true: 0.0
        prob_given_false: 0.01
      - entity_id: input_boolean.home_travelling_mode
        platform: state
        to_state: on
        prob_given_true: 0.0
        prob_given_false: 0.01
      - entity_id: input_boolean.home_party_mode
        platform: state
        to_state: on
        prob_given_true: 0.4
        prob_given_false: 0.1

  - name: Guest bathroom - Presence - Combined
    platform: group
    unique_id: 0b69d9d8-00f7-4599-ab48-1b156cbfb0eb
    device_class: occupancy
    entities:
      - binary_sensor.guest_bathroom_motion_occupancy
      - binary_sensor.guest_bathroom_door_opening

input_boolean:
  guest_bathroom_occupied:
    name: Guest bathroom - Occupied
    icon: mdi:human-male-female

sensor:
  - platform: history_stats
    name: Guest bathroom - Motion ratio in the last 10m
    entity_id: binary_sensor.guest_bathroom_motion_occupancy
    state: "on"
    type: ratio
    #start: "{{ (now() + timedelta(minutes=-10)) }}"
    end: "{{ now() }}"
    duration:
      minutes: 10

template:
  - trigger:
    - id: Door
      platform: state
      entity_id:
        - binary_sensor.guest_bathroom_door
      from:
        - "off"
        - "on"
      to:
        - "off"
        - "on"
    - id: Motion
      platform: state
      entity_id:
        - binary_sensor.guest_bathroom_motion_iaszone
      to:
        - "on"
    binary_sensor:
      - name: Guest bathroom - Motion while door is closed
        unique_id: 2a4cfac8-4ece-4855-b282-0010f459ab5e
        state: "{{ (trigger.id == 'Motion') and is_state('binary_sensor.guest_bathroom_door', 'off') }}"
        attributes:
          triggered_by: "{{ trigger.entity_id }}"
          last_triggered: "{{ now() }}"
          trigger: "{{ trigger }}"
          door: "{{ states('binary_sensor.guest_bathroom_door') }}"
          motion: "{{ states('binary_sensor.guest_bathroom_motion_iaszone') }}"
