automation:
  - alias: Guest bathroom - Lights - Motion based
    id: '1644684428323'
    description: ''
    use_blueprint:
      path: EdwardTFN/light_motion_illuminance_2_levels.yaml
      input:
        lumens_entity: sensor.guest_bathroom_motion_illuminance
        light_target: light.guest_bathroom_all_lights
        light_level_high: 50
        light_level_dimmer: 25
        no_motion_wait_to_dimming: 60
        no_motion_wait_to_off: 30
        max_lumens: 15
        motion_entity: binary_sensor.guest_bathroom_presence_combined

light:
  - platform: group
    name: "Guest bathroom - All lights"
    unique_id: ad3f8239-b80f-416b-b83a-78a36bde6e36
    entities:
      - light.guest_bathroom_light
