automation:
  - alias: Hall - Door - Announce to Alexa
    id: '1669284651718'
    description: ''
    trigger:
    - platform: state
      entity_id:
      - binary_sensor.hall_front_door
      from: 'off'
      to: 'on'
    condition: []
    action:
    - action: notify.send_message
      target:
        entity_id: notify.kitchen_announce
      data:
        message: The front door is open
    mode: single
