binary_sensor:
  - name: Office - Presence
    platform: group
    unique_id: f4bc1d3b-a99f-47c4-95f6-99833b3d5451
    device_class: presence
    entities:
      - binary_sensor.office_presence_occupancy
      - binary_sensor.esp32_s3_box_3_5a7750_presence_detect
