substitutions:
  device_name: "guest-room-panel"
  friendly_name: Guest room - Panel
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

packages:
  #core:               !include packages/Blackymas/esphome/nspanel_esphome_core.yaml
  #standard:           !include packages/Blackymas/esphome/nspanel_esphome_standard.yaml
  #nspanel_package:    !include packages/Blackymas/nspanel_esphome.yaml
  remote_package:
    url: https://github.com/edwardtfn/NSPanel-Easy
    ref: latest #v9999.99.9
    refresh: 10s
    files:
      - nspanel_esphome.yaml # Base package including TFT transfer
  wifi: !include packages/config_wifi.yaml

  manual_ip: !include
    file: packages/config_manual_ip.yaml
    vars:
      ip: !secret ip_guest_room_panel
