automation:
  - alias: Home - Weather - Windows are open
    id: '1663627849757'
    description: ''
    trigger:
      - platform: state
        entity_id:
          - weather.home
        to: rainy
      - platform: state
        entity_id:
          - weather.home
        to: snowy-rainy
      - platform: state
        entity_id:
          - weather.home
        to: lightning-rainy
      - platform: state
        entity_id:
          - weather.home
        to: snowy
      - platform: state
        entity_id:
          - weather.home
        to: windy
      - platform: state
        entity_id:
          - weather.home
        to: windy-variant
    condition:
      - condition: template
        value_template: "{{ (\n  states.binary_sensor \n  | selectattr('attributes.device_class',
          'defined') \n  | selectattr('attributes.device_class','eq','window') \n  | selectattr('state',
          'eq', 'on') \n  | map(attribute='name') \n  | list \n  | count) > 0 \n}}"
    action:
      - service: notify.signal_group_home
        data:
          message: "The weather is changing and the following windows are open:\n- {{
            states.binary_sensor \n    | selectattr('attributes.device_class', 'defined')
            \n    | selectattr('attributes.device_class','eq','window') \n    | selectattr('state',
            'eq', 'on') \n    | map(attribute='name') \n    | list \n    | join('\n    -
            ') }}"
    mode: single
  - alias: Home - Humidifiers - At least one humidifier requires attention
    id: '1638151457747'
    trigger:
      - platform: numeric_state
        entity_id:
          - climate.bathroom_thermostat
          - climate.guest_room_thermostat
          - climate.guest_room_closet_thermostat
          - climate.kitchen_thermostat
          - climate.living_room_thermostat
        attribute: current_humidity
        below: 35
        for:
          minutes: 5
      - platform: numeric_state
        entity_id:
          - sensor.bedroom_hygrometer_humidity
          - sensor.corridor_air_quality_humidity
          - sensor.office_hygrometer_humidity
        below: 35
        for:
          minutes: 5
    action:
      - variables:
          announcement: "{{ (state_attr('input_select.phrases_low_humidity', 'options') | random).replace('room_name', area_name(trigger.entity_id) | default('the apartment')) }}"
      - service: notify.signal_group_home
        data:
          message: >
            {{ announcement }}

            Humidity: {{ trigger.to_state.state | round(0) }}%
      #- if:
      #    - condition: state
      #      entity_id: schedule.home_quite_hours
      #      state: "off"
      #    - condition: state
      #      entity_id: input_boolean.home_empty
      #      state: "off"
      #  then:
      #    - service: notify.alexa_media
      #      data:
      #        message: "{{ announcement }}"
      #        target: "Kitchen{{ (', ' ~ area_name(trigger.entity_id) | default(None)) if area_name(trigger.entity_id) != 'Kitchen' }}"

    mode: single

input_select:
  phrases_low_humidity:
    name: Phrases - Low humidity in a room
    #unique_id: cdc79d47-45f7-4afb-8d8b-7f2442ba237d
    options:
      - "Alert: Humidity levels in the room_name are low."
      - "Warning: Low humidity levels detected in the room_name."
      - Humidity in the room_name is below optimal levels.
      - "Attention: Low humidity has been detected in the room_name."
      - Humidity levels are dangerously low in the room_name.
      - Low humidity detected in the room_name, please take necessary precautions.
      - Humidity levels in the room_name are outside the optimal range.
      - Humidity readings indicate a low level in the room_name.
      - Low humidity levels may cause discomfort in the room_name.
      - Humidity levels have fallen below the recommended range in the room_name.
      - Please be advised, humidity levels are low in the room_name.
      - Low humidity levels in the room_name can lead to dryness and discomfort.
      - Humidity levels in the room_name are not at an optimal level.
      - Low humidity can negatively impact air quality in the room_name.
      - "Alert: Humidity is too low for comfort in room_name."
      - Humidity levels are insufficient for healthy living in room_name.
      - Low humidity can cause dry skin and respiratory issues in room_name.
      - Humidity levels indicate a dry environment in room_name.
      - "Warning: Low humidity can damage furniture and wooden floors in room_name."
      - Low humidity can cause static electricity buildup in room_name.
      - Humidity levels are too low for proper plant growth in room_name.
      - "Alert: Low humidity levels can cause allergies and respiratory problems in room_name."
      - Humidity levels are below the recommended range for indoor comfort in room_name.
      - Low humidity can lead to dehydration and fatigue in room_name.
      - "Attention: Low humidity can cause nosebleeds and dry throat in room_name."
      - Humidity readings suggest a dry and uncomfortable environment in room_name.
      - Low humidity levels can cause damage to musical instruments in room_name.
      - Humidity levels are insufficient for maintaining proper indoor humidity in room_name.
      - Low humidity can cause eye irritation and skin dryness in room_name.
      - "Alert: Humidity levels are below optimal levels for healthy living in room_name."
      - Low humidity detected in room_name - please take action.
      - "Warning: Humidity levels are low in room_name - check the humidity level."

script:
  climate_toggle:
    alias: Home - Climate - Toggle a thermostat
    icon: mdi:thermometer
    mode: restart
    sequence:
      - service: climate.set_hvac_mode
        data_template:
          hvac_mode: '{{ iif(is_state(climate, ''off''), ''auto'', ''off'') }}'
          entity_id: '{{ climate }}'

template:
  - binary_sensor:
      - name: Home - Heating
        unique_id: ccdc9413-8b08-4d95-837a-8883886df7f6
        device_class: heat
        state: "{{ (this.attributes.entities | default([]) | count | int(0)) > 0 }}"
        attributes:
          entities: "{{ expand(integration_entities('HomeKit Controller - Tado')) | selectattr('domain', 'eq', 'climate') | selectattr('attributes.hvac_action', 'eq', 'heating') | map(attribute='entity_id') | list }}"

  - sensor:
    - name: Home - Sun elevation
      unique_id: d725f9db-2e6c-42ae-afaa-e1cac9edf391
      unit_of_measurement: "°"
      state: >-
        {{ state_attr('sun.sun', 'elevation') }}

    - name: Home - Sun azimuth
      unique_id: 2375d2d3-5883-461c-9afb-4e337bcc9a16
      unit_of_measurement: "°"
      state: >-
        {{ state_attr('sun.sun', 'azimuth') }}

    #- platform: template
    #  sensors: weather_just_icon:
    #  name: "Home - Weather"
    #  icon_template: >-
    #    {% if is_state("weather.climacell_hourly","clear-day") %} mdi:weather-sunny {% elif is_state("weather.climacell_hourly","sunny") %} mdi:weather-sunny {% elif is_state("weather.climacell_hourly","clear") %} mdi:weather-sunny {% elif is_state("weather.climacell_hourly","clear-night") %} mdi:weather-night {% elif is_state("weather.climacell_hourly","rainy") %} mdi:weather-rainy {% elif is_state("weather.climacell_hourly","pouring") %} mdi:weather-pouring {% elif is_state("weather.climacell_hourly","snow") %} mdi:weather-snowy {% elif is_state("weather.climacell_hourly","fog") %} mdi:weather-fog {% elif is_state("weather.climacell_hourly","sleet") %} mdi:weather-partly-snowy-rainy {% elif is_state("weather.climacell_hourly","wind") %} mdi:weather-windy {% elif is_state("weather.climacell_hourly","cloudy") %} mdi:weather-cloudy {% elif is_state("weather.climacell_hourly","partlycloudy") %} mdi:weather-partly-cloudy {% elif is_state("weather.climacell_hourly","partly-cloudy-night") %} mdi:weather-night-partly-cloudy {% elif is_state("weather.climacell_hourly","hail") %} mdi:weather-hail {% elif is_state("weather.climacell_hourly","lightning") %} mdi:weather-lightning {% elif is_state("weather.climacell_hourly","tstorm") %} mdi:weather-lightning-rainy {% endif %}
    - name: Home - Visibility
      unique_id: c0e7b7dc-6d69-4b86-99de-c84553386800
      unit_of_measurement: "Km"
      state: >-
        {{ state_attr('weather.home', 'visibility') }}

    - name: Civil Solar day status
      unique_id: 3ce1befd-f340-4c84-ad9c-beaf400550ce
      availability: '{{ has_value("sun.sun") and is_number(state_attr("sun.sun", "elevation")) }}'
      state: >-
        {% set sun_angle = state_attr('sun.sun', 'elevation') | float(0) %}
        {% if sun_angle < -6 %}
          night
        {% elif sun_angle < 0 %}
          twilight
        {% else %}
          day
        {% endif %}
      icon: >-
        {% if is_state("sensor.civil_solar_day_status", "night") %}
          mdi:weather-night
        {% elif is_state("sensor.civil_solar_day_status", "day") %}
          mdi:weather-sunny
        {% elif is_state("sensor.civil_solar_day_status", "twilight") %}
          {% if is_state_attr('sun.sun', 'rising', true) %}
            mdi:weather-sunset-up
          {% else %}
            mdi:weather-sunset-down
          {% endif %}
        {% else %}
          mdi:help
        {% endif %}

  - trigger:
    - platform: state
      entity_id:
        - sun.sun
      attribute: rising
      from:
        - true
        - True
        - on
      to:
        - false
        - False
        - off
    sensor:
      - name: Sun - Max elevation
        unique_id: 07603c28-6f7d-4589-99b1-5b5862e9bf2c
        unit_of_measurement: "°"
        icon: mdi:white-balance-sunny
        state: "{{ state_attr('sun.sun', 'elevation') | float(0) }}"
        attributes:
          last_update: "{{ now() }}"

  - trigger:
    - platform: time
      at: "00:00:00"
    - platform: template
      value_template: "{{ states('sensor.home_weather_outdoor_temperature') > states('sensor.home_weather_outdoor_temperature_daily_max') }}"
    sensor:
      - name: Home - Weather - Outdoor temperature - Daily max
        unique_id: home_weather_outdoor_temperature_daily_max
        unit_of_measurement: "°C"
        device_class: temperature
        icon: mdi:thermometer-chevron-up
        state: "{{ states('sensor.home_weather_outdoor_temperature')}}"
        attributes:
          datetime: "{{ now() }}"

  - trigger:
    - platform: time
      at: "00:00:00"
    - platform: template
      value_template: "{{ states('sensor.home_weather_outdoor_temperature') < states('sensor.home_weather_outdoor_temperature_daily_min') }}"
    sensor:
      - name: Home - Weather - Outdoor temperature - Daily min
        unique_id: home_weather_outdoor_temperature_daily_min
        unit_of_measurement: "°C"
        device_class: temperature
        icon: mdi:thermometer-chevron-down
        state: "{{ states('sensor.home_weather_outdoor_temperature')}}"
        attributes:
          datetime: "{{ now() }}"
